function: via_cutback
info: {}
module: gdsfactory.components.via_cutback
name: via_cutback
settings:
  layer1: HEATER
  layer2: M1
  min_pad_pitch: 10.0
  num_vias: 200.0
  pad:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
        - HEATER
        - M2
        - MTOP
      vias:
        - null
        - function: via
          module: gdsfactory.components.via
          settings:
            enclosure: 2
            layer: VIA1
        - function: via
          module: gdsfactory.components.via
          settings:
            layer: VIA2
  pad_size:
    - 100
    - 100
  via_layer: VIAC
  via_spacing: 30.0
  via_width: 5.0
  wire_pad_inclusion: 2.0
  wire_width: 10.0
