info:
  length: 10
  pdk: fab_c
  route_info_length: 10
  route_info_type: xs_0cd5d5fa
  route_info_weight: 10
  route_info_xs_0cd5d5fa_length: 10
  width: 1
name: straight_nc_CSstrip_nc
settings:
  cross_section: strip_nc
